server:
  port: 80

spring:
  application:
    name: consul-consumer-order
    #使用consul作为注册中心
  cloud:
    consul:
      host: 172.16.101.229
      port: 8500
      discovery:
        service-name: ${spring.application.name}